In [78]:
"""
Data Can be: Text, Image, Video, Audio, Tabular data etc.

Tabular data => Pandas DataFrame
Pandas: analyze, clean, explore, manipulate tabular data
"""

'\nData Can be: Text, Image, Video, Audio, Tabular data etc.\n\nTabular data => Pandas DataFrame\nPandas: analyze, clean, explore, manipulate tabular data\n'

In [79]:
import pandas as pd

In [80]:
health_data_table = {
    "height": [1.8, 1.6, 1.7, 1.9],
    "weight": [70, 60, 65, 80],
    "bmi": [21.6, 23.4, 22.5, None],
}

health_data_frame = pd.DataFrame(health_data_table)

print(type(health_data_frame))

<class 'pandas.core.frame.DataFrame'>


In [81]:
health_data_frame.head()  # first 5 rows

height  weight   bmi
0     1.8      70  21.6
1     1.6      60  23.4
2     1.7      65  22.5
3     1.9      80   NaN

In [82]:
health_data_frame.head(2) #first 2 rows


height  weight   bmi
0     1.8      70  21.6
1     1.6      60  23.4

In [83]:
health_data_frame.tail() #last 5 rows

height  weight   bmi
0     1.8      70  21.6
1     1.6      60  23.4
2     1.7      65  22.5
3     1.9      80   NaN

In [84]:
health_data_frame.shape

(4, 3)

In [85]:
health_data_frame.info()  # info about the data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   height  4 non-null      float64
 1   weight  4 non-null      int64  
 2   bmi     3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes


In [86]:
health_data_frame.describe() # summary statistics of the data frame on numerical columns

height     weight    bmi
count  4.000000   4.000000   3.00
mean   1.750000  68.750000  22.50
std    0.129099   8.539126   0.90
min    1.600000  60.000000  21.60
25%    1.675000  63.750000  22.05
50%    1.750000  67.500000  22.50
75%    1.825000  72.500000  22.95
max    1.900000  80.000000  23.40

In [87]:
values = health_data_frame.values  # get the values of the data frame as a numpy array
print(values)
print(type(values))

[[ 1.8 70.  21.6]
 [ 1.6 60.  23.4]
 [ 1.7 65.  22.5]
 [ 1.9 80.   nan]]
<class 'numpy.ndarray'>


In [88]:
cols = health_data_frame.columns
print(cols)

Index(['height', 'weight', 'bmi'], dtype='object')


In [89]:
health_data_frame.columns = ["Height(Feet)", "Weight(kg)", "BMI"]  # rename columns
print(health_data_frame.head())

   Height(Feet)  Weight(kg)   BMI
0           1.8          70  21.6
1           1.6          60  23.4
2           1.7          65  22.5
3           1.9          80   NaN


In [ ]:
health_data_frame.to_csv(path_or_buf="data/health_data.csv", index=False)  # save the data frame to a csv file

In [ ]:
my_health_data = pd.read_csv("data/health_data.csv")

In [92]:
my_health_data.head()

Height(Feet)  Weight(kg)   BMI
0           1.8          70  21.6
1           1.6          60  23.4
2           1.7          65  22.5
3           1.9          80   NaN

In [ ]:
df = pd.read_csv("data/homelessness.csv")

In [94]:
df.head()

Unnamed: 0              region       state  individuals  family_members  \
0           0  East South Central     Alabama       2570.0           864.0   
1           1             Pacific      Alaska       1434.0           582.0   
2           2            Mountain     Arizona       7259.0          2606.0   
3           3  West South Central    Arkansas       2280.0           432.0   
4           4             Pacific  California     109008.0         20964.0   

   state_pop  
0    4887681  
1     735139  
2    7158024  
3    3009733  
4   39461588

In [95]:
""" Sorting data
"""

sorted_df = df.sort_values(by=["region"]) 
# sorted_df = df.sort_values(by=["region", "individuals"], ascending=False) 

sorted_df.head()

Unnamed: 0              region      state  individuals  family_members  \
35          35  East North Central       Ohio       6929.0          3320.0   
49          49  East North Central  Wisconsin       2740.0          2167.0   
22          22  East North Central   Michigan       5209.0          3142.0   
13          13  East North Central   Illinois       6752.0          3891.0   
14          14  East North Central    Indiana       3776.0          1482.0   

    state_pop  
35   11676341  
49    5807406  
22    9984072  
13   12723071  
14    6695497

In [96]:
sorted_df2 = df.sort_values(by=["region", "individuals"]) 
sorted_df2.head()

Unnamed: 0              region      state  individuals  family_members  \
49          49  East North Central  Wisconsin       2740.0          2167.0   
14          14  East North Central    Indiana       3776.0          1482.0   
22          22  East North Central   Michigan       5209.0          3142.0   
13          13  East North Central   Illinois       6752.0          3891.0   
35          35  East North Central       Ohio       6929.0          3320.0   

    state_pop  
49    5807406  
14    6695497  
22    9984072  
13   12723071  
35   11676341

In [97]:
sorted_df3 = df.sort_values(by=["region"]) 
sorted_df3.head()

Unnamed: 0              region      state  individuals  family_members  \
35          35  East North Central       Ohio       6929.0          3320.0   
49          49  East North Central  Wisconsin       2740.0          2167.0   
22          22  East North Central   Michigan       5209.0          3142.0   
13          13  East North Central   Illinois       6752.0          3891.0   
14          14  East North Central    Indiana       3776.0          1482.0   

    state_pop  
35   11676341  
49    5807406  
22    9984072  
13   12723071  
14    6695497

In [98]:
sorted_df4 = df.sort_values(by=["region", "individuals"]
    , ascending=[True, False]
) 
sorted_df4.head()

Unnamed: 0              region      state  individuals  family_members  \
35          35  East North Central       Ohio       6929.0          3320.0   
13          13  East North Central   Illinois       6752.0          3891.0   
22          22  East North Central   Michigan       5209.0          3142.0   
14          14  East North Central    Indiana       3776.0          1482.0   
49          49  East North Central  Wisconsin       2740.0          2167.0   

    state_pop  
35   11676341  
13   12723071  
22    9984072  
14    6695497  
49    5807406

In [99]:
import numpy as np 
individuals = np.array(df["individuals"])
print(individuals)
print(type(individuals))

[  2570.   1434.   7259.   2280. 109008.   7607.   2280.    708.   3770.
  21443.   6943.   4131.   1297.   6752.   3776.   1711.   1443.   2735.
   2540.   1450.   4914.   6811.   5209.   3993.   1024.   3776.    983.
   1745.   7058.    835.   6048.   1949.  39827.   6451.    467.   6929.
   2823.  11139.   8163.    747.   3082.    836.   6139.  19199.   1904.
    780.   3928.  16424.   1021.   2740.    434.]
<class 'numpy.ndarray'>


In [100]:
new_df = df[["region", "family_members"]]
print(new_df.head())

               region  family_members
0  East South Central           864.0
1             Pacific           582.0
2            Mountain          2606.0
3  West South Central           432.0
4             Pacific         20964.0


In [101]:
df_mountain = df[df["region"] == "Mountain"]
print(df_mountain.head())

    Unnamed: 0    region     state  individuals  family_members  state_pop
2            2  Mountain   Arizona       7259.0          2606.0    7158024
5            5  Mountain  Colorado       7607.0          3250.0    5691287
12          12  Mountain     Idaho       1297.0           715.0    1750536
26          26  Mountain   Montana        983.0           422.0    1060665
28          28  Mountain    Nevada       7058.0           486.0    3027341


In [102]:
df_gt_10k = df[df["individuals"] > 10000]
print(df_gt_10k.head())

    Unnamed: 0              region       state  individuals  family_members  \
4            4             Pacific  California     109008.0         20964.0   
9            9      South Atlantic     Florida      21443.0          9587.0   
32          32        Mid-Atlantic    New York      39827.0         52070.0   
37          37             Pacific      Oregon      11139.0          3337.0   
43          43  West South Central       Texas      19199.0          6111.0   

    state_pop  
4    39461588  
9    21244317  
32   19530351  
37    4181886  
43   28628666  


In [103]:
is_family_lt_1k_mask = df["family_members"] < 1000
is_region_pecific_mask = df["region"] == "Pacific"

In [104]:
df["total_members"] = df["individuals"] + df["family_members"]
print(df.head())

   Unnamed: 0              region       state  individuals  family_members  \
0           0  East South Central     Alabama       2570.0           864.0   
1           1             Pacific      Alaska       1434.0           582.0   
2           2            Mountain     Arizona       7259.0          2606.0   
3           3  West South Central    Arkansas       2280.0           432.0   
4           4             Pacific  California     109008.0         20964.0   

   state_pop  total_members  
0    4887681         3434.0  
1     735139         2016.0  
2    7158024         9865.0  
3    3009733         2712.0  
4   39461588       129972.0  


In [105]:
new_df = df.query("family_members < 1000 and region == 'Pacific'")
print(new_df.head())

   Unnamed: 0   region   state  individuals  family_members  state_pop  \
1           1  Pacific  Alaska       1434.0           582.0     735139   

   total_members  
1         2016.0  


In [106]:
new_df.columns

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop', 'total_members'],
      dtype='object')

In [107]:
new_df = new_df.drop(columns=["Unnamed: 0"])
print(new_df)

    region   state  individuals  family_members  state_pop  total_members
1  Pacific  Alaska       1434.0           582.0     735139         2016.0


In [108]:
print("Mean: ", new_df["individuals"].mean())
print("Median: ", new_df["individuals"].median())
print("Max: ", new_df["individuals"].max())
print("Min: ", new_df["individuals"].min())
print("Sum: ", new_df["individuals"].sum())

Mean:  1434.0
Median:  1434.0
Max:  1434.0
Min:  1434.0
Sum:  1434.0


In [110]:
new_df[["individuals", "family_members"]].mean()

individuals       1434.0
family_members     582.0
dtype: float64

In [ ]:
def normalize(col):
    mean = col.mean()
    std = col.std()
    normalized_col = (col - mean) / std

    return normalized_col

normalized_df = new_df[["individuals", "family_members"]].agg(normalize)