In [2]:
""" Multidimentional numpy arrays
    Mathematical objects: 
        Scalar: 4 or 4.5 etc. => 0 Dimensional
        Vector: [4, 5] => 1 Dimensional
        Matrix: [ [1, 2, 3], 
                  [4, 5, 6] ] => 2(n) Dimensional
        Tensor: An array with more than 2 dimensions
        [[[1, 2], [3, 4]], 
         [[5, 6], [7, 8]]] => 3 Dimensional
        [[[[1, 2], [3, 4]], 
          [[5, 6], [7, 8]]]] => 4 Dimensional
        [[[[[1, 2], [3, 4]], 
           [[5, 6], [7, 8]]]]] => 5 Dimensional
"""

' Multidimentional numpy arrays\n    Mathematical objects: \n        Scalar: 4 or 4.5 etc. => 0 Dimensional\n        Vector: [4, 5] => 1 Dimensional\n        Matrix: [ [1, 2, 3], \n                  [4, 5, 6] ] => 2(n) Dimensional\n        Tensor: An array with more than 2 dimensions\n        [[[1, 2], [3, 4]], \n         [[5, 6], [7, 8]]] => 3 Dimensional\n        [[[[1, 2], [3, 4]], \n          [[5, 6], [7, 8]]]] => 4 Dimensional\n        [[[[[1, 2], [3, 4]], \n           [[5, 6], [7, 8]]]]] => 5 Dimensional\n'

In [3]:
import numpy as np

In [4]:
scaler = np.array(57)
print(scaler) # 0 brackets => 0D 

57


In [5]:
vector = np.array([1, 2, 3, 4, 5])
vector # 1 bracket => 1D 
print(vector)

[1 2 3 4 5]


In [6]:
matrix = np.array([ [1, 2],
                    [3, 4],
                    [5, 6] ]
                 ) # 2 nested brackets => 2D 
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
print("dimention of scaler: ", scaler.ndim)
print("dimention of vector: ", vector.ndim)
print("dimention of matrix: ", matrix.ndim)

dimention of scaler:  0
dimention of vector:  1
dimention of matrix:  2


In [8]:
"""Numpy indexing 
    1. Non-negative indexing (0, 1, 2, ... n-1)
    2. Negative indexing (-1, -2, -3, ... -n)

    array = [1, 2, 3, 4, 5]
    #        0  1  2  3  4
    #       -5 -4 -3 -2 -1
"""

array = np.array([1, 2, 3, 4, 5])
print(array[1])
print(array[-4])

2
2


In [9]:
my_2d_array = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]])

print(my_2d_array[1, 2])
print(my_2d_array[-2, -2])
print(my_2d_array[1, -2])

7
7
7


In [10]:
""" Numpy Slicing 


"""

array = np.array([1, 2, 3, 4, 5])
#start=0:stop=n:step=1 (default values)
print(array[::])
print(array[1:5:2])
print(array[2:4])


[1 2 3 4 5]
[2 4]
[3 4]


In [11]:
my_2d_array = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]])

#                row   column
print(my_2d_array[0:2, 1:3])

[[2 3]
 [6 7]]


In [12]:
#                 row   column
print(my_2d_array[0:3:2, 0:4:2])

[[ 1  3]
 [ 9 11]]


In [13]:
""" 
    Numpy Array Reshape
    1. Reshape: Change the shape of an array without changing its data
        step-a) Flatten the array (to 1D)
        step-b) Reshape the array from flattened to desired shape
        
        condition: number of elements in the original array must be equal to the number of elements in the reshaped array
    2. Resize: Change the shape and size of an array
"""

my_2d_array = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12],
     [13, 14, 15]
    ]
)

print(my_2d_array.shape) # (5, 3)

(5, 3)


In [14]:
my_2d_array_reshaped = my_2d_array.reshape(3, 5)
print(my_2d_array_reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [15]:
print(my_2d_array_reshaped.shape)

(3, 5)


In [16]:
my_2d_array_reshaped2 = my_2d_array.reshape(1, 3, 5)
print(my_2d_array_reshaped2)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [17]:
zero_arr = np.zeros((3, 4, 2, 2))
zero_arrreshaped = zero_arr.reshape(2, 2, 12)
print(zero_arrreshaped)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [18]:
print(zero_arrreshaped.shape)

(2, 2, 12)


In [19]:
zero_arrreshaped = zero_arr.reshape(2, -1, 12) # -1 means that numpy will calculate the value for you
print(zero_arrreshaped.shape)                  # It only works for just one -1

(2, 2, 12)


In [ ]:
""" 
    Numpy filterring
"""

my_array = np.array([1, 2, 3, 4, 5, 6])

filter_mask = [True, False, True, False, True, False]  # Only keep odd numbers
filtered_array = my_array[filter_mask]
print(filtered_array)



[1 3 5]


In [22]:
indices = [1, 3, 5]
filtered_array2 = my_array[indices]
print(filtered_array2)

[2 4 6]


In [26]:
""" 
    Numpy Vectorization:
    It refers to the process of performing operations on entire arrays parallely.
"""

my_arr = np.array([1, 2, 3, 4, 5])


# Conventional way (loop)
for val in my_arr:
    if val%2 == 1:
        print(val)


# Vectorized way
my_arr[my_arr%2 == 1]


1
3
5


array([1, 3, 5])

In [29]:
my_arr+=5
print(my_arr)

[ 6  7  8  9 10]


In [ ]:
""" Numpy Broadcasting:
     Converting a lower dimension into higher dimension for vectorization

    Condition: lower dimension must be 1*higher dimension
    Ex:     (6, 7, 7) and (6,)
    (6,) => (6, 1, 1) => (6, 7, 7)
                        #> Broadcasted
     
     Ex:       (6,  3,  8) and (6, 2)
     (6, 2) => (6,  2,  1) => No broadcast
                   #X => Not possible  
"""

w = np.array([1, 2])
x = np.array([ [3, 4],
               [5, 6],
               [7, -8],
               [-5, -3]
            ])

print(w.shape)
print(x.shape)


(2,)
(4, 2)


In [33]:
print(w * x)  # Broadcasting w to match the shape of x

[[  3   8]
 [  5  12]
 [  7 -16]
 [ -5  -6]]


In [ ]:
print(w + x)  # It works for +, -, *, / as well

[[ 4  6]
 [ 6  8]
 [ 8 -6]
 [-4 -1]]


In [41]:
""" Numpy Axis 
        1. First dimension: Axis 0
        2. Second dimension: Axis 1
        3. Third dimension: Axis 2
        .
        .
        .
        n. nth dimension: Axis n-1
"""

my_2d_array = np.array(
    [[1, 5, -2],
     [0, 1, 9]]
)

print(my_2d_array.sum())
print(my_2d_array.shape)

14
(2, 3)


In [ ]:
# Sum along axis

sum_row_wise = my_2d_array.sum(axis=1) # Sum along axis 1 
sum_col_wise = my_2d_array.sum(axis=0) # Sum along axis 0 
print(sum_row_wise)
print(sum_row_wise.shape)
print(sum_col_wise)
print(sum_col_wise.shape)


[ 4 10]
(2,)
[1 6 7]
(3,)


In [ ]:
my_3d = np.zeros((3, 2, 4))

print(my_3d.sum(axis=0).shape)  # Sum along axis 0 (2, 4)
print(my_3d.sum(axis=1).shape)  # Sum along axis 1 (3, 4)
print(my_3d.sum(axis=2).shape)  # Sum along axis 2 (3, 2)

(2, 4)
(3, 4)
(3, 2)


In [ ]:
""" Numpy Random
"""

print(np.random.rand()) #0-less then 1
print(np.random.rand(5)) #random array

0.7496460069980266
[0.16058916 0.0792051  0.81974316 0.72305949 0.82810617]


In [53]:
print(np.random.randint(100)) #0-100
arr = np.random.randint(100, size=(5, 2))
print(arr)

34
[[75 52]
 [12 10]
 [79 21]
 [70 80]
 [79 95]]


In [54]:
np.random.shuffle(arr)
print(arr)

[[70 80]
 [75 52]
 [79 21]
 [79 95]
 [12 10]]


In [56]:
""" Useful numpy methods
"""

probabilities = np.array([0.3, 0.1, 0.4, 0.2])
print(probabilities)

probabilities_sorted = np.sort(probabilities)
print(probabilities_sorted)

probabilities_reverse_sorted = np.sort(probabilities)[::-1]
print(probabilities_reverse_sorted)

[0.3 0.1 0.4 0.2]
[0.1 0.2 0.3 0.4]
[0.4 0.3 0.2 0.1]


In [57]:
index_max = np.argmax(probabilities)
print(index_max)

index_min = np.argmin(probabilities)
print(index_min)

2
1


In [59]:
arr = np.array([1, 5, 1, 1, 5, 7])

new_arr = np.split(arr, 3)  # Split the array into 3 equal parts
print(new_arr)
print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[array([1, 5]), array([1, 1]), array([5, 7])]
[1 5]
[1 1]
[5 7]
